### ISSUE TITLE
: MISCONF Redis is configured to save RDB snapshots

### ISSUE THREAD

**Issue by dudeisbrendan03** [Websoft9/ansible-awx#22]
**Describe the bug**

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [x] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [x] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

Latest

**OS**

- [ ] Ubuntu18.x
- [x] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

## Bug reproduce

1. Run script to auto-configure
2. Create project and sync

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
2021-03-01 22:34:04,550 ERROR    awx.main.commands.run_callback_receiver encountered an error communicating with redis
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/worker/callback.py", line 56, in read
    res = self.redis.blpop(settings.CALLBACK_QUEUE, timeout=1)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/client.py", line 1865, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/client.py", line 878, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/redis/connection.py", line 752, in read_response
    raise response```

### Bug Screenshot

![image](https://user-images.githubusercontent.com/6009600/109568899-7b4ef580-7adf-11eb-9160-68a01e61e33c.png)

## Your suggestion

**The reason of Bug**

After checking volumes created it looks like redis doesn't have any persistent storage or anywhere it's able to write rdb snapshots, consider making a volume with the correct permissions or disabling stop-writes-on-bgsave-error.

**Your solution for Bug**

Disable snapshots, set stop-writes-on-bgsave-error to no or create a volume allowing dump.rdb to be stored and persist

**Comment by qiaofeng1227** [comment]
to dudeisbrendan03 👍 Thank you very much for your advice, We merged your code.

**Comment by dudeisbrendan03** [comment]
No problem, useful repo! Not too great with ansible but I'll take a look into sorting redis out properly later
